<?xml version="1.0"?>
<!-- Thesis Quadruped Leg -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="height_upperleg" value="0.25" /> <!-- UpperLeg Height -->
  <xacro:property name="height_lowerleg" value="0.15" /> <!-- LowerLeg Height -->
  <xacro:property name="height_foot" value="0.05" /> <!-- Foot Height -->

  <xacro:property name="height_leg" value="${height_upperleg+height_lowerleg+height_foot}"/>

  <xacro:property name="width_leg" value="0.05" /> <!-- leg width -->

  <xacro:property name="mass_leg" value="5" /> <!-- leg width -->  

  <xacro:property name="mass_upperleg" value="${mass_leg*0.65}"/>
  <xacro:property name="mass_lowerleg" value="${mass_leg*0.15}"/>
  <xacro:property name="mass_foot" value="${mass_leg*0.2}"/>

<xacro:macro name="leg" params="side reflectx reflecty parent">
<!-- Shoulder Joint -->
<joint type="revolute" name="${side}_shoulder">
        	<parent link = "${parent}"/>
        	<child link = "${side}_upperleg"/>
		<origin xyz = "${width_body/2*reflectx} ${length_body/2*reflecty}  0" rpy="0 0 0"/>
        	<axis xyz="1 0 0"/>
		<dynamics damping="0.7"/>
		<limit effort="100" velocity="1.0" lower="${-PI/3}" upper="${PI/3}"/>
	</joint> 

<!-- Upper Leg--> 
   <link name="${side}_upperleg">
          	<collision>
          	  <origin xyz="0 0 ${-height_upperleg/2}" rpy="0 0 0"/>
                  <geometry>
	            <box size="${width_leg} ${width_leg} ${height_upperleg}"/>
                  </geometry>
		</collision>

		<visual>
          	  <origin xyz="0 0 ${-height_upperleg/2}" rpy="0 0 0"/>
                  <geometry>
	            <box size="${width_leg} ${width_leg} ${height_upperleg}"/>
                  </geometry>
		  <material name="orange"/>
		</visual>

		<inertial>
	          <origin xyz="0 0 ${-height_upperleg/2}" rpy="0 0 0"/>
	          <mass value="${mass_upperleg}"/>
	          <inertia
		    ixx="${mass_upperleg / 12.0 * (width_leg*width_leg + height_upperleg*height_upperleg)}" ixy="0.0" ixz="0.0"
		    iyy="${mass_upperleg / 12.0 * (height_upperleg*height_upperleg + width_leg*width_leg)}" iyz="0.0"
		    izz="${mass_upperleg / 12.0 * (width_leg*width_leg + width_leg*width_leg)}"/>
		</inertial>

		
  </link> 
			
<!-- Knee Joint--> 

	<joint type="revolute" name="${side}_knee">
        	<parent link = "${side}_upperleg"/>
        	<child link = "${side}_lowerleg"/>
		<origin xyz = "0 0 ${-height_upperleg}" rpy="0 0 0"/>
        	<axis xyz="1 0 0"/>
		<dynamics damping="0.7"/>  
		<limit effort="100" velocity="1.0" lower="${-PI/3}" upper="${PI/3}"/>     	
       </joint> 

<!-- Lower Leg--> 
   <link name="${side}_lowerleg">
          	<collision>
          	  <origin xyz="0 0 -${height_lowerleg/2}" rpy="0 0 0"/>
                  <geometry>
	            <box size="${width_leg} ${width_leg} ${height_lowerleg}"/>
                  </geometry>
		</collision>

		<visual>
          	  <origin xyz="0 0 -${height_lowerleg/2}" rpy="0 0 0"/>
                  <geometry>
	            <box size="${width_leg} ${width_leg} ${height_lowerleg}"/>
                  </geometry>
		  <!--<material name="orange"/>-->
		</visual>

		<inertial>
	          <origin xyz="0 0 -${height_lowerleg/2}" rpy="0 0 0"/>
	          <mass value="${mass_lowerleg}"/>
	          <inertia
		    ixx="${mass_lowerleg / 12.0 * (width_leg*width_leg + height_lowerleg*height_lowerleg)}" ixy="0.0" ixz="0.0"
		    iyy="${mass_lowerleg / 12.0 * (height_lowerleg*height_lowerleg + width_leg*width_leg)}" iyz="0.0"
		    izz="${mass_lowerleg / 12.0 * (width_leg*width_leg + width_leg*width_leg)}"/>
		</inertial>

		
  </link> 

<!-- Ankle Joint--> 

	<joint type="revolute" name="${side}_ankle">
        	<parent link = "${side}_lowerleg"/>
        	<child link = "${side}_foot"/>
		<origin xyz = "0 0 ${-height_lowerleg}" rpy="0 0 0"/>
        	<axis xyz="1 0 0"/>
		<dynamics damping="0.7"/>
		<limit effort="100" velocity="1.0"/>        	
       </joint> 

<!-- Foot--> 
   <link name="${side}_foot">
          	<collision>
          	  <origin xyz="0 0 -${height_foot/2}" rpy="0 0 0"/>
                  <geometry>
	            <box size="${width_leg} ${width_leg} ${height_foot}"/>
                  </geometry>
		</collision>

		<visual>
          	  <origin xyz="0 0 -${height_foot/2}" rpy="0 0 0"/>
                  <geometry>
	            <box size="${width_leg} ${width_leg} ${height_foot}"/>
                  </geometry>
		  <!--<material name="orange"/>-->
		</visual>

		<inertial>
	          <origin xyz="0 0 -${height_foot/2}" rpy="0 0 0"/>
	          <mass value="${mass_foot}"/>
	          <inertia
		    ixx="${mass_foot / 12.0 * (width_leg*width_leg + height_foot*height_foot)}" ixy="0.0" ixz="0.0"
		    iyy="${mass_foot / 12.0 * (height_foot*height_foot + width_leg*width_leg)}" iyz="0.0"
		    izz="${mass_foot / 12.0 * (width_leg*width_leg + width_leg*width_leg)}"/>
		</inertial>

		
  </link> 

<!-- Gazebo References -->
  <gazebo reference="${side}_upperleg">
    <material>Gazebo/Black</material>
  </gazebo>

  <gazebo reference="${side}_lowerleg">
    <material>Gazebo/Orange</material>
  </gazebo>

  <gazebo reference="${side}_foot">
    <material>Gazebo/Red</material>
  </gazebo>


<!-- Transmissions -->
<transmission name="${side}_tran_shoulder">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="${side}_shoulder">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="${side}_motor_shoulder">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

<transmission name="${side}_tran_knee">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="${side}_knee">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="${side}_motor_knee">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

<transmission name="${side}_tran_ankle">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="${side}_ankle">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="${side}_motor_ankle">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
  


  </xacro:macro>
</robot>
